version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test

env:
  - CGO_ENABLED=0
  - GO_LD_FLAGS="-extldflags "-static" -s -w -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.Version={{.Version}} -X main.Revision={{.ShortCommit}}"

builds:
  - id: go-curling-linux
    binary: go-curling
    ldflags:
      - "{{.Env.GO_LD_FLAGS}}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
    goarm:
      - "7"

  - id: go-curling-darwin
    binary: go-curling
    ldflags:
      - "{{.Env.GO_LD_FLAGS}}"
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"

  - id: go-curling-freebsd
    binary: go-curling
    ldflags:
      - "{{.Env.GO_LD_FLAGS}}"
    goos:
      - freebsd
    goarch:
      - amd64

  - id: go-curling-windows
    binary: go-curling
    ldflags:
      - "{{.Env.GO_LD_FLAGS}}"
    goos:
      - windows
    goarch:
      - amd64
      - arm64

nfpms:
  id: go-curling-package
  package_name: go-curling
  vendor: Chris Wiegand
  homepage: https://github.com/cdwiegand/go-curling
  maintainer: Chris Wiegand <chris@wiegandtech.net>
  description: A re-creation of the venerable curl to make HTTP/S calls
  license: MIT
  builds:
    - go-curling-linux
  formats:
    - apk
    - deb
    - rpm
    - archlinux
  deb:
    lintian_overrides:
      - statically-linked-binary
      - changelog-file-missing-in-native-package

chocolateys:
  - name: go-curling
    ids:
      - archive-zip
    package_source_url: https://github.com/cdwiegand/go-curling
    owners: Chris Wiegand
    title: go-curling
    api_key: "{{ .Env.CHOCOLATEY_KEY }}"
    authors: Chris Wiegand <chris@wiegandtech.net>
    project_url: https://github.com/cdwiegand/go-curling
    url_template: "https://github.com/cdwiegand/go-curling/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    icon_url: "https://rawcdn.githack.com/foo/bar/efbdc760-395b-43f1-bf69-ba25c374d473/icon.png"
    copyright: 2024 Chris Wiegand
    license_url: https://github.com/cdwiegand/go-curling/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/cdwiegand/go-curling
    docs_url: https://github.com/cdwiegand/go-curling/blob/main/README.md
    release_notes: "https://github.com/cdwiegand/go-curling/releases/tag/v{{ .Version }}"
    summary: A re-creation of the venerable curl to make HTTP/S calls
    description: |
      go-curling installer package.
      A re-creation of the venerable curl to make HTTP/S calls

archives:
  - id: archive-tgz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tgz
    builds:
      - go-curling-linux
      - go-curling-darwin
      - go-curling-freebsd
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      - SECURITY.md
  - id: archive-zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    builds:
      - go-curling-linux
      - go-curling-darwin
      - go-curling-freebsd
      - go-curling-windows
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      - SECURITY.md
  - id: binary-not-windows
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: binary
    builds:
      - go-curling-linux
      - go-curling-darwin
      - go-curling-freebsd
  - id: binary-windows-exe
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.exe"
    format: binary
    builds:
      - go-curling-windows

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--checksums.txt"

release:
  draft: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
